---
apiVersion: v1
kind: Service
metadata:
  name: digitizer-backend
  namespace: digitizer
spec:
  selector:
    app: digitizer-backend
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: digitizer-frontend
  namespace: digitizer
spec:
  selector:
    app: digitizer-frontend
  ports:
    - port: 3000
      targetPort: 3000
